package uah; // Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class Test1GeneratedFromSideFile {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {

    // A lined added by us! the rest of the code is autorgenerated
    System.setProperty("webdriver.gecko.driver", "./src/test/resources/geckodriver");

    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void test1() {
    driver.get("https://escuelapolitecnica.uah.es/");
    driver.manage().window().setSize(new Dimension(752, 615));
    assertThat(driver.getTitle(), is("Escuela Politécnica Superior - UAH"));
    assertThat(
        driver.findElement(By.cssSelector("address")).getText(),
        is("Campus Universitario. Ctra. Madrid-Barcelona, Km. 33,600. Alcalá de Henares (Madrid)"));
    driver.findElement(By.linkText("Aula Virtual")).click();
  }
}
